### ISSUE TITLE
pydantic error

### ISSUE THREAD

**Issue by mendykrauss** [HealthITAU/pyconnectwise#3]
```
D:\Documents\programming\cw-automations\venv\lib\site-packages\pydantic\_internal\_config.py:257: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
D:\Documents\programming\cw-automations\venv\lib\site-packages\pydantic\_internal\_fields.py:126: UserWarning: Field "model_number" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
```

Getting this error when trying a simple request:

`api.company.companies.get()`

**Comment by Yoshify** [comment]
Hi Mendykrauss. Could you please run `pip show pydantic` and confirm which version of Pydantic you're running? I think this may be because of changes in the latest pre-release versions of Pydantic.

**Comment by mendykrauss** [comment]
```
Name: pydantic
Version: 2.0.1
Summary: Data validation using Python type hints
Home-page:
Author:
Author-email: Samuel Colvin <s@muelcolvin.com>, Eric Jolibois <em.jolibois@gmail.com>, Hasan Ramezani <hasan.r67@gmail.com>, Adrian Garcia Badaracco <1755071+adriangb@users.noreply.github.com>, Terrence Dorsey <terry@pydantic.dev>, David Montague <david@pydantic.dev>
License:
Location: d:\documents\programming\cw-automations\venv\lib\site-packages
Requires: annotated-types, pydantic-core, typing-extensions
Required-by: pyconnectwise
```

**Comment by Yoshify** [comment]
Could you please try downgrading to version 1.10.11 and confirm if that resolves the issue?

**Comment by mendykrauss** [comment]
That worked.

Now getting a new error!

```
Traceback (most recent call last):
  File "D:\Documents\programming\cw-automations\application\testing_new_pip.py", line 12, in <module>
    companies = api.finance.invoices.make_request('GET').build_url()
  File "D:\Documents\programming\cw-automations\venv\lib\site-packages\pyconnectwise\endpoints\base\connectwise_endpoint.py", line 155, in make_request
    raise Exception(
Exception: Request failed with status code 403: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Bad request.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: nBpIesqmduZepYy7W9b-HxPJR8j9NGn1r4SDTvGj9qXp2mfmdks24A==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by Yoshify** [comment]
Glad that worked - I'm going to need to lock the Pydantic version at 1.10.11 until support for >2.0 is added. Thank you for raising this.

Just having a look at the code in the traceback - it's likely because of an invalid URL being created. There isn't any real error handling around this yet.

You shouldn't need to use the code like this `companies = api.finance.invoices.make_request('GET').build_url()`

If you're looking to grab companies, it's as simple as using `companies = api.company.companies.get()`
If you're looking to grab invoices, `invoices = api.finance.invoices.get()`
In almost all cases you shouldn't need to call `make_request()` or `build_url()` yourself - you should only need to interact with the named request functions (`get()`, `post()`, etc)
